## Question 1: Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [46]:
import numpy as np

In [16]:
array1 = np.array([21, 19])
array2 = np.array([1, 7])
print("Original numbers:")
print(array1)
print(array2)
print("Comparison - greater : ", np.greater(array1, array2))
print("Comparison - greater_equal : ", np.greater_equal(array1,array2))
print("Comparison - less : ", np.less(array1, array2))
print("Comparison - less_equal : ", np.less_equal(array1, array2))

Original numbers:
[21 19]
[1 7]
Comparison - greater :  [ True  True]
Comparison - greater_equal :  [ True  True]
Comparison - less :  [False False]
Comparison - less_equal :  [False False]


## Question 2: Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,5)


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## Question 3: Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [14]:
array = np.array([[21,19],[1,7]])
print("Original array:")
print(array)
print("\nSum of all the elements:", np.sum(array))
print("\nSum of each column:", np.sum(array, axis=0))
print("\nSum of each row:", np.sum(array, axis=1))

Original array:
[[21 19]
 [ 1  7]]

Sum of all the elements: 48

Sum of each column: [22 26]

Sum of each row: [40  8]


## Question 4: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [37]:
#from scipy.special import exp10

In [38]:
x = np.array([21,19])
y = np.array([1,7])

In [39]:
np.add(x,y)

array([22, 26])

In [40]:
np.subtract(x,y)

array([20, 12])

In [41]:
np.multiply(x,y)

array([ 21, 133])

In [43]:
np.divide(x,y)

array([21.        ,  2.71428571])

## Question 5: Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [21]:
array = np.array([0,30,45,60,90]) 
print("sin: array of angles given in degrees")
print(array * np.pi / 180.)
print("\ncos: array of angles given in degrees")
print(array * np.pi / 180.)
print("\ntangent: array of angles given in degrees")
print(array * np.pi / 180.)

sin: array of angles given in degrees
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

cos: array of angles given in degrees
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

tangent: array of angles given in degrees
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


## Question 6: Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [1]:
import pandas as pd

In [24]:
data = {'Name' : ['Sandeep','Sharath','soujan','Datta','Akhil','Prashanth','Chandu'],'Age' : [25,27,25,25,23,27,25],
        'Course' : ['AIML & Python','AIML','AIML','AIML','AIML','AIML','AIML'],
        'Qualified' : ['Yes','Yes','Yes','Yes','Yes','No','No']}

# Index also works instead of lables.
labels = ['a','b','c','d','e','f','g']

In [26]:
df = pd.DataFrame(data, labels)
#display(df) 
df

Name  Age         Course Qualified
a    Sandeep   25  AIML & Python       Yes
b    Sharath   27           AIML       Yes
c     soujan   25           AIML       Yes
d      Datta   25           AIML       Yes
e      Akhil   23           AIML       Yes
f  Prashanth   27           AIML        No
g     Chandu   25           AIML        No

## Question 7: Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame

In [29]:
print('Select Specific Columns')
df[['Name','Course']]

Select Specific Columns


Name         Course
a    Sandeep  AIML & Python
b    Sharath           AIML
c     soujan           AIML
d      Datta           AIML
e      Akhil           AIML
f  Prashanth           AIML
g     Chandu           AIML

## Question 8 : Write a Pandas program to join the two given DataFrames along rows and assign all data.

In [38]:
data_frame1 = {'Employee_id' : ['emp001','emp002','emp003','emp004'],
                            'Employee_name' : ['Sandeep','Akhil','Sharath','Prashanth'],
                            'Designation': ['Data-Analyst', 'Data-Analyst', 'ML-Eng', 'Software Developer']}
index1 = ['a','b','c','d']
d1 = pd.DataFrame(data_frame1, index1)
d1

Employee_id Employee_name         Designation
e      emp001       Sandeep        Data-Analyst
f      emp002         Akhil        Data-Analyst
g      emp003       Sharath              ML-Eng
h      emp004     Prashanth  Software Developer

In [40]:
data_frame2 = {'Employee_id' : ['emp005','emp006','emp007','emp008'],
                            'Employee_name' : ['Chandu','Vamsi','Datta','Siva'],
                            'Designation': ['Software Engineer','Softawre Developer','Software Engineer','Web-Developer']}
index2 = ['e','f','g','h']
d2 = pd.DataFrame(data_frame2, index2)
d2

Employee_id Employee_name         Designation
e      emp005        Chandu   Software Engineer
f      emp006         Vamsi  Softawre Developer
g      emp007         Datta   Software Engineer
h      emp008          Siva       Web-Developer

In [ ]:
# Concatinaqting Two Data Frames.

In [43]:
print('Joining the Two Data Frames along with the Rows: ')
result_data_frame = pd.concat([d1, d2])
result_data_frame

Joining the Two Data Frames along with the Rows: 


Employee_id Employee_name         Designation
e      emp001       Sandeep        Data-Analyst
f      emp002         Akhil        Data-Analyst
g      emp003       Sharath              ML-Eng
h      emp004     Prashanth  Software Developer
e      emp005        Chandu   Software Engineer
f      emp006         Vamsi  Softawre Developer
g      emp007         Datta   Software Engineer
h      emp008          Siva       Web-Developer

## Question 9: Write a Pandas program to delete missing values of a given DataFrame. Display True or False.

In [57]:
import numpy as np
data = {'Name' : ['Sandeep', 'Akhil', 'Sharath', 'Prashanth'],
        'Age' : [25,24,np.nan,np.nan]}
index = ['a','b','c','d']
df1 = pd.DataFrame(data , index)
df1

Name   Age
a    Sandeep  25.0
b      Akhil  24.0
c    Sharath   NaN
d  Prashanth   NaN

In [58]:
# Deleting the null Values.
df1.dropna()

Name   Age
a  Sandeep  25.0
b    Akhil  24.0

In [59]:
# Showing the rows where the values are null.
df1['Age'].isnull()

a    False
b    False
c     True
d     True
Name: Age, dtype: bool

## Question 10: Write a Pandas program to create and display a one dimensional array like oject containing an array of data.

In [60]:
# Array od Data
array_data = pd.Series([1,2,3,4,5,6,7,8,9,21.01,19.07], index = ['a','b','c','d','e','f','g','h','i','j','k'])

In [61]:
array_data

a     1.00
b     2.00
c     3.00
d     4.00
e     5.00
f     6.00
g     7.00
h     8.00
i     9.00
j    21.01
k    19.07
dtype: float64