## Question 1: Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [2]:
import numpy as np

In [16]:
array1 = np.array([21, 19])
array2 = np.array([1, 7])
print("Original numbers:")
print(array1)
print(array2)
print("Comparison - greater : ", np.greater(array1, array2))
print("Comparison - greater_equal : ", np.greater_equal(array1,array2))
print("Comparison - less : ", np.less(array1, array2))
print("Comparison - less_equal : ", np.less_equal(array1, array2))

Original numbers:
[21 19]
[1 7]
Comparison - greater :  [ True  True]
Comparison - greater_equal :  [ True  True]
Comparison - less :  [False False]
Comparison - less_equal :  [False False]


## Question 2: Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,5)


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## Question 3: Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [14]:
array = np.array([[21,19],[1,7]])
print("Original array:")
print(array)
print("\nSum of all the elements:", np.sum(array))
print("\nSum of each column:", np.sum(array, axis=0))
print("\nSum of each row:", np.sum(array, axis=1))

Original array:
[[21 19]
 [ 1  7]]

Sum of all the elements: 48

Sum of each column: [22 26]

Sum of each row: [40  8]


## Question 4: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [37]:
#from scipy.special import exp10

In [38]:
x = np.array([21,19])
y = np.array([1,7])

In [39]:
np.add(x,y)

array([22, 26])

In [40]:
np.subtract(x,y)

array([20, 12])

In [41]:
np.multiply(x,y)

array([ 21, 133])

In [43]:
np.divide(x,y)

array([21.        ,  2.71428571])

## Question 5: Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [21]:
array = np.array([0,30,45,60,90]) 
print("sin: array of angles given in degrees")
print(array * np.pi / 180.)
print("\ncos: array of angles given in degrees")
print(array * np.pi / 180.)
print("\ntangent: array of angles given in degrees")
print(array * np.pi / 180.)

sin: array of angles given in degrees
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

cos: array of angles given in degrees
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

tangent: array of angles given in degrees
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
