In [3]:
import numpy as np

# Considering sample data as follows
# X = (hours studying, hours sleeping), y = score on test
xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float)  # input data
y = np.array(([92], [86], [89]), dtype=float)  # output

# scale units
xAll = xAll / np.amax(xAll, axis=0)  # scaling input data
y = y / 100  # scaling output data (max test score is 100)

# split data
X = np.split(xAll, [3])[0]  # training data
xPredicted = np.split(xAll, [3])[1]  # testing data

y = np.array(([92], [86], [89]), dtype=float)
y = y / 100  # max test score is 100


class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(
            X,
            self.W1)  # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(
            self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2.T
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(
            self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))


NN = Neural_Network()
for i in range(1000):  # trains the NN 1,000 times
    print("--> " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" +
          str(np.mean(np.square(y - NN.forward(X)))))  # mean sum squared loss
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

--> 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.51398966]
 [0.52756906]
 [0.51604311]]
Loss: 
0.1383994947004342


--> 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.55854911]
 [0.57044358]
 [0.55736786]]
Loss: 
0.10837793570735647


--> 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.59675799]
 [0.60707429]
 [0.59290223]]
Loss: 
0.08557463354353019


--> 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.62927047]
 [0.63810739]
 [0.62325998]]
Loss: 
0.06830341019694598


--> 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.65689434]
 [0.66435819]
 [0.64917367]]
Loss: 
0.05516587563789772


--> 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6

Predicted Output: 
[[0.87408812]
 [0.86814093]
 [0.86099084]]
Loss: 
0.0010052355819756135


--> 50

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.87483489]
 [0.86884238]
 [0.86176   ]]
Loss: 
0.0009718574480370484


--> 51

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.87555138]
 [0.86951527]
 [0.86249836]]
Loss: 
0.000940853582376217


--> 52

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.87623919]
 [0.87016109]
 [0.86320752]]
Loss: 
0.0009120311118767538


--> 53

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.87689983]
 [0.87078125]
 [0.86388898]]
Loss: 
0.00088521508677462


--> 54

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.87753469]
 [0.8

 [0.87822141]]
Loss: 
0.0005181526075508235


--> 94

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8908959 ]
 [0.88379243]
 [0.87839648]]
Loss: 
0.0005159232806628604


--> 95

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89105938]
 [0.88394023]
 [0.87856654]]
Loss: 
0.0005138061342582123


--> 96

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8912182 ]
 [0.88408358]
 [0.87873176]]
Loss: 
0.0005117946857629349


--> 97

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89137252]
 [0.88422261]
 [0.8788923 ]]
Loss: 
0.0005098828527082046


--> 98

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89152249]
 [0.88435747]
 [0.87904831]]
Loss: 
0.00050806492

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89585993]
 [0.887989  ]
 [0.8835475 ]]
Loss: 
0.0004692539443158236


--> 157

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89589229]
 [0.88801074]
 [0.88358069]]
Loss: 
0.00046899700391512194


--> 158

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89592388]
 [0.88803175]
 [0.88361309]]
Loss: 
0.0004687437005768444


--> 159

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89595474]
 [0.88805205]
 [0.88364471]]
Loss: 
0.0004684938544712359


--> 160

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89598487]
 [0.88807164]
 [0.88367557]]
Loss: 
0.00046824729502617865


--> 161

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 


 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89682641]
 [0.88845699]
 [0.88452441]]
Loss: 
0.00045893260514379163


--> 206

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89683747]
 [0.88845819]
 [0.88453525]]
Loss: 
0.0004587449544909752


--> 207

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89684833]
 [0.8884592 ]
 [0.88454588]]
Loss: 
0.0004585576803432378


--> 208

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89685898]
 [0.88846   ]
 [0.88455628]]
Loss: 
0.0004583707684466087


--> 209

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89686943]
 [0.8884606 ]
 [0.88456647]]
Loss: 
0.0004581842052545111


--> 210

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[

0.00045037539215957845


--> 253

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89718895]
 [0.88835323]
 [0.8848676 ]]
Loss: 
0.0004501971768612622


--> 254

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89719404]
 [0.88834874]
 [0.88487217]]
Loss: 
0.00045001907579362253


--> 255

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89719908]
 [0.88834418]
 [0.88487666]]
Loss: 
0.00044984108760331206


--> 256

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89720405]
 [0.88833957]
 [0.8848811 ]]
Loss: 
0.00044966321100130697


--> 257

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89720896]
 [0.8883349 ]
 [0.88488547]]
Loss: 
0.00044948544475973876


-

Loss: 
0.0004421087053204503


--> 300

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89738015]
 [0.88809731]
 [0.88503123]]
Loss: 
0.00044193504864516327


--> 301

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89738349]
 [0.88809121]
 [0.88503394]]
Loss: 
0.0004417614798545155


--> 302

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89738681]
 [0.88808509]
 [0.88503663]]
Loss: 
0.00044158799877625936


--> 303

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89739011]
 [0.88807896]
 [0.88503931]]
Loss: 
0.0004414146052440791


--> 304

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89739339]
 [0.88807282]
 [0.88504196]]
Loss: 
0.0004412412990973205

--> 344

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89751378]
 [0.88781824]
 [0.88513651]]
Loss: 
0.0004343793360813415


--> 345

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89751659]
 [0.88781173]
 [0.88513867]]
Loss: 
0.000434209517551333


--> 346

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8975194 ]
 [0.88780522]
 [0.88514082]]
Loss: 
0.0004340397823907361


--> 347

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8975222 ]
 [0.88779871]
 [0.88514297]]
Loss: 
0.00043387013053583647


--> 348

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.897525  ]
 [0.88779219]
 [0.88514511]]
Loss: 
0.00043370056192353567


--> 349

Input (scaled): 
[[0

Predicted Output: 
[[0.89763573]
 [0.88752328]
 [0.88522858]]
Loss: 
0.0004268192004478039


--> 390

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89763837]
 [0.8875167 ]
 [0.88523054]]
Loss: 
0.00042665307629114754


--> 391

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.897641  ]
 [0.88751013]
 [0.8852325 ]]
Loss: 
0.00042648703299087096


--> 392

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89764362]
 [0.88750355]
 [0.88523446]]
Loss: 
0.00042632107049548007


--> 393

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89764625]
 [0.88749698]
 [0.88523641]]
Loss: 
0.00042615518875358123


--> 394

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.897

--> 440

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89776788]
 [0.88718891]
 [0.88532637]]
Loss: 
0.000418448906417697


--> 441

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89777044]
 [0.88718239]
 [0.88532826]]
Loss: 
0.00041828684173897374


--> 442

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.897773  ]
 [0.88717586]
 [0.88533014]]
Loss: 
0.0004181248553727904


--> 443

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89777556]
 [0.88716934]
 [0.88533202]]
Loss: 
0.0004179629472705145


--> 444

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89777812]
 [0.88716282]
 [0.8853339 ]]
Loss: 
0.00041780111738354747


--> 445

Input (scaled): 
[[0

--> 507

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89793806]
 [0.8867556 ]
 [0.88545104]]
Loss: 
0.00040776142101092076


--> 508

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89794059]
 [0.8867492 ]
 [0.88545288]]
Loss: 
0.0004076044975308657


--> 509

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89794311]
 [0.88674279]
 [0.88545473]]
Loss: 
0.0004074476491864166


--> 510

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89794563]
 [0.88673639]
 [0.88545657]]
Loss: 
0.0004072908759313705


--> 511

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89794816]
 [0.88673   ]
 [0.88545841]]
Loss: 
0.00040713417771954505


--> 512

Input (scaled): 
[[

Loss: 
0.00039939393681036046


--> 562

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89807636]
 [0.88640625]
 [0.88555175]]
Loss: 
0.00039924100537698493


--> 563

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89807886]
 [0.88639995]
 [0.88555357]]
Loss: 
0.0003990881466327948


--> 564

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89808137]
 [0.88639366]
 [0.88555539]]
Loss: 
0.000398935360533403


--> 565

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89808387]
 [0.88638736]
 [0.88555721]]
Loss: 
0.00039878264703448516


--> 566

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89808638]
 [0.88638107]
 [0.88555903]]
Loss: 
0.0003986300060917151

Predicted Output: 
[[0.89827833]
 [0.88590242]
 [0.88569807]]
Loss: 
0.00038709108769618435


--> 644

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89828081]
 [0.88589628]
 [0.88569986]]
Loss: 
0.00038694397230929536


--> 645

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89828329]
 [0.88589014]
 [0.88570166]]
Loss: 
0.0003867969260811532


--> 646

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89828577]
 [0.885884  ]
 [0.88570345]]
Loss: 
0.0003866499489700239


--> 647

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89828825]
 [0.88587787]
 [0.88570524]]
Loss: 
0.0003865030409342146


--> 648

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89829

Predicted Output: 
[[0.89839464]
 [0.88561579]
 [0.88578196]]
Loss: 
0.0003802507540205516


--> 691

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89839711]
 [0.88560974]
 [0.88578374]]
Loss: 
0.0003801068444882


--> 692

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89839958]
 [0.88560369]
 [0.88578551]]
Loss: 
0.00037996300218671943


--> 693

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89840205]
 [0.88559764]
 [0.88578729]]
Loss: 
0.00037981922707581474


--> 694

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89840451]
 [0.88559159]
 [0.88578906]]
Loss: 
0.00037967551911524244


--> 695

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8984069

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89852995]
 [0.88528556]
 [0.8858792 ]]
Loss: 
0.000372434520821404


--> 746

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89853241]
 [0.88527961]
 [0.88588096]]
Loss: 
0.00037229424994120885


--> 747

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89853486]
 [0.88527366]
 [0.88588272]]
Loss: 
0.0003721540441201197


--> 748

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89853731]
 [0.88526771]
 [0.88588448]]
Loss: 
0.00037201390331946586


--> 749

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89853976]
 [0.88526176]
 [0.88588623]]
Loss: 
0.0003718738275006075


--> 750

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[

Predicted Output: 
[[0.89865465]
 [0.88498422]
 [0.88596849]]
Loss: 
0.00036536285814597896


--> 797

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89865708]
 [0.88497836]
 [0.88597023]]
Loss: 
0.00036522585657060524


--> 798

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89865952]
 [0.8849725 ]
 [0.88597198]]
Loss: 
0.0003650889181184146


--> 799

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89866196]
 [0.88496664]
 [0.88597372]]
Loss: 
0.00036495204275218025


--> 800

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89866439]
 [0.88496078]
 [0.88597546]]
Loss: 
0.0003648152304346938


--> 801

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8986

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89878586]
 [0.88467014]
 [0.88606212]]
Loss: 
0.0003580541875165501


--> 851

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89878828]
 [0.88466437]
 [0.88606385]]
Loss: 
0.00035792054199205206


--> 852

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8987907 ]
 [0.88465861]
 [0.88606557]]
Loss: 
0.00035778695761915733


--> 853

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89879312]
 [0.88465284]
 [0.8860673 ]]
Loss: 
0.00035765343436209624


--> 854

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89879555]
 [0.88464708]
 [0.88606902]]
Loss: 
0.0003575199721851144


--> 855

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 

 [0.89]]
Predicted Output: 
[[0.89891383]
 [0.88436674]
 [0.88615311]]
Loss: 
0.000351054411260242


--> 904

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89891623]
 [0.88436106]
 [0.88615482]]
Loss: 
0.0003509239580865221


--> 905

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89891864]
 [0.88435538]
 [0.88615653]]
Loss: 
0.00035079356420425755


--> 906

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89892105]
 [0.88434971]
 [0.88615824]]
Loss: 
0.00035066322957905366


--> 907

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89892345]
 [0.88434403]
 [0.88615995]]
Loss: 
0.00035053295417652487


--> 908

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 


--> 998

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89914118]
 [0.88383458]
 [0.886314  ]]
Loss: 
0.0003389214132606909


--> 999

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89914356]
 [0.88382906]
 [0.88631568]]
Loss: 
0.000338796442591089


Predicted data based on trained weights: 
Input (scaled): 
[[1. 1.]]
Output: 
[[0.90106318]]
